/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlnv;

import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author longl
 */
public class JFrameNV extends javax.swing.JFrame {

    /**
     * Creates new form JFrameNV
     */
    public JFrameNV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtSoSP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbbPhanXuong = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtSanPhamChuan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLuong = new javax.swing.JTextField();
        btnTinhLuong = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        lbERR = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Mã NV");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));
        getContentPane().add(txtMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 11, 281, -1));
        getContentPane().add(txtSoSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 42, 281, -1));

        jLabel2.setText("Số sản phẩm");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, -1, -1));

        jLabel3.setText("Phân xưởng");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 73, -1, -1));

        cbbPhanXuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        cbbPhanXuong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbPhanXuongItemStateChanged(evt);
            }
        });
        getContentPane().add(cbbPhanXuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 73, 76, -1));

        jLabel4.setText("Số sản phẩm chuẩn");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 76, -1, -1));

        txtSanPhamChuan.setEditable(false);
        txtSanPhamChuan.setText("300");
        getContentPane().add(txtSanPhamChuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 73, 74, -1));

        jLabel5.setText("Tiền lương");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 121, -1, -1));

        txtLuong.setEditable(false);
        txtLuong.setBackground(new java.awt.Color(0, 204, 255));
        txtLuong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtLuong.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLuong.setText("0");
        getContentPane().add(txtLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 111, 197, -1));

        btnTinhLuong.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTinhLuong.setText("Tính lương");
        btnTinhLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhLuongActionPerformed(evt);
            }
        });
        getContentPane().add(btnTinhLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 157, -1, -1));

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 157, -1, -1));

        btnRemove.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRemove.setText("Xóa");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 157, -1, -1));

        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEdit.setText("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 157, -1, -1));

        btnClose.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnClose.setText("Đóng");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 157, -1, -1));

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Phan xưởng", "Số sản phẩm", "Vượt chuẩn"
            }
        ));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblNhanVien);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 410, 180));

        lbERR.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lbERR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 410, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTinhLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhLuongActionPerformed
        // TODO add your handling code here:
      
        try 
        {                        
            Integer.parseInt(txtSoSP.getText());            
        } 
        catch (NumberFormatException e) 
        {
            JOptionPane.showMessageDialog(null, "Nhap sai, nhap lai");
        }
        int sp = Integer.parseInt(txtSoSP.getText());
        int spc = Integer.parseInt(txtSanPhamChuan.getText());
        int Luong;
        if(sp > spc)    
            Luong = (sp - spc)*30000 + spc*20000;        
        else
            Luong = sp*20000;
        txtLuong.setText(String.valueOf(Luong));
    }//GEN-LAST:event_btnTinhLuongActionPerformed

    private void cbbPhanXuongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbPhanXuongItemStateChanged
        // Cach 1
        /*if( evt.getStateChange() == ItemEvent.SELECTED)
        {
           Object item = evt.getItem();
           if(item.equals("A"))
               txtSanPhamChuan.setText("300");
           else
               txtSanPhamChuan.setText("500");
        }*/
        if(evt.getItem().equals("A"))
            txtSanPhamChuan.setText("300");
           else
               txtSanPhamChuan.setText("500");
        
    }//GEN-LAST:event_cbbPhanXuongItemStateChanged

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblNhanVien.getModel();
        try 
        {                        
            Integer.parseInt(txtSoSP.getText());            
        } 
        catch (NumberFormatException e) 
        {
            lbERR.setText("So san pham chi duoc nhap so");
        }
        if(!txtMa.getText().trim().equals(""))
        {
            NhanVien nv = new NhanVien(txtMa.getText(),cbbPhanXuong.getSelectedItem().toString(),Integer.parseInt(txtSoSP.getText()));
            String vuotchuan = "";
            if (nv.VuotChuan())
                vuotchuan = "x";            
            model.addRow(new Object[]{nv.getMaNV(),nv.getPhanXuong(),txtSoSP.getText(),vuotchuan});
        }
        else
            lbERR.setText("Khong duoc de trong ma san pham");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        lbERR.setText("");
        DefaultTableModel model = (DefaultTableModel)tblNhanVien.getModel();
        NhanVien nv = new NhanVien(txtMa.getText(),cbbPhanXuong.getSelectedItem().toString(),Integer.parseInt(txtSoSP.getText()));
        String vuotchuan = "";
        if (nv.VuotChuan())
            vuotchuan = "x";
        if(tblNhanVien.getSelectedRow() == -1){
            if(tblNhanVien.getRowCount() == 0){
                lbERR.setText("Khong co du lieu");
            }
            else
                lbERR.setText("Chua chon nhan vien");
        }
        else{
            model.setValueAt(nv.getMaNV(), tblNhanVien.getSelectedRow(), 0);
            model.setValueAt(nv.getPhanXuong(), tblNhanVien.getSelectedRow(), 1);
            model.setValueAt(String.valueOf(nv.getSoSP()), tblNhanVien.getSelectedRow(), 2);
            model.setValueAt(vuotchuan, tblNhanVien.getSelectedRow(), 3);
        }    
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblNhanVien.getModel();
        txtMa.setText(model.getValueAt(tblNhanVien.getSelectedRow(), 0).toString());
        cbbPhanXuong.setSelectedItem(model.getValueAt(tblNhanVien.getSelectedRow(), 1).toString());
        txtSoSP.setText(model.getValueAt(tblNhanVien.getSelectedRow(), 2).toString());
        
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblNhanVien.getModel();
        if(tblNhanVien.getSelectedRow() == -1){
            if(tblNhanVien.getRowCount() == 0){
                lbERR.setText("Khong co du lieu");
            }
            else
                lbERR.setText("Chua chon nhan vien");
        }
        else{
            model.removeRow(tblNhanVien.getSelectedRow());
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    public class NhanVien
    {
        String MaNV;
        String PhanXuong;
        int SoSP;
        public NhanVien(){};
        public NhanVien(String ma,String px,int sp)
        {
            MaNV = ma;
            PhanXuong = px;
            SoSP = sp;
        }
        public String getMaNV()
        {
            return this.MaNV;
        }
        public void setMaNV(String ma)
        {
            this.MaNV = ma;
        }
        public String getPhanXuong()
        {
            return this.PhanXuong;
        }
        public void setPhanXuong(String px)
        {
            this.PhanXuong = px;
        }
        public int getSoSP()
        {
            return this.SoSP;
        }
        public void setSoSP(int sp)
        {
            this.SoSP = sp;
        }
        public int getChuan()
        {
            if(PhanXuong.equals("A"))
                return 300;
            else
                return 500;
        }
      
        public boolean VuotChuan()
        {
            return SoSP > getChuan();
        }
        public int TinhLuong()
        {
            if(VuotChuan())
                return (SoSP - getChuan())*30000 + getChuan()*20000;
            else
                return SoSP*20000;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnTinhLuong;
    private javax.swing.JComboBox<String> cbbPhanXuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbERR;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtSanPhamChuan;
    private javax.swing.JTextField txtSoSP;
    // End of variables declaration//GEN-END:variables
}
