/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PL;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author longl
 */
public class GUI_MAIN extends javax.swing.JFrame {

    /**
     * Creates new form GUI_MAIN
     */
    public GUI_MAIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGUI_NV = new javax.swing.JButton();
        btnGUI_QuanLy_KH = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGUI_NV.setText("Quản lý nhân viên");
        btnGUI_NV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGUI_NVActionPerformed(evt);
            }
        });

        btnGUI_QuanLy_KH.setText("Quản lý khách hàng");
        btnGUI_QuanLy_KH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGUI_QuanLy_KHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(318, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGUI_QuanLy_KH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGUI_NV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(142, 142, 142))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(btnGUI_NV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGUI_QuanLy_KH)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGUI_QuanLy_KHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGUI_QuanLy_KHActionPerformed
        try {
            // TODO add your handling code here:
            new GUI_KHACH_HANG().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(GUI_MAIN.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGUI_QuanLy_KHActionPerformed

    private void btnGUI_NVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGUI_NVActionPerformed
        try {
            // TODO add your handling code here:
            new GUI_NHAN_VIEN().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(GUI_MAIN.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGUI_NVActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGUI_NV;
    private javax.swing.JButton btnGUI_QuanLy_KH;
    // End of variables declaration//GEN-END:variables
}
